apiVersion: v1
kind: Pod
metadata:
  name: tmp-results-fetcher-func
  namespace: gp-engine-malof
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: sihang-test-pvc
  containers:
    - name: fetcher
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "--- Peptides Functional Dense Results ---"
          ls /mnt/pvc/GT_PE/Benchmarking-PEs/logs/verify_peptides_func_dense_*.log | xargs grep "Best so far"
          echo "--- Peptides Functional GAT Results ---"
          ls /mnt/pvc/GT_PE/Benchmarking-PEs/logs/verify_peptides_func_gat_*.log | xargs grep "Best so far"
      volumeMounts:
        - name: data
          mountPath: "/mnt/pvc"
  restartPolicy: Never
