accelerator: cuda:0
dataset:
  edge_encoder: true
  edge_encoder_bn: false
  edge_encoder_name: Bond
  format: OGB
  name: peptides-structural
  node_encoder: true
  node_encoder_bn: false
  node_encoder_name: Atom
  task: graph
  task_type: regression
  transductive: false
gnn:
  act: relu
  batchnorm: true
  dim_inner: 96
  dropout: 0.0
  head: default
  layers_post_mp: 2
  layers_pre_mp: 0
gt:
  attn:
    O_e: true
    act: relu
    clamp: 5.0
    edge_enhance: false
    full_attn: true
    norm_e: true
    signed_sqrt: true
  attn_dropout: 0.2
  batch_norm: true
  dim_hidden: 96
  dropout: 0.05
  layer_norm: false
  layer_type: GritTransformer
  layers: 4
  n_heads: 8
  sparse: false
metric_agg: argmin
metric_best: mae
mlflow:
  name: peptides-struct-GRIT-noPE
  project: Exp
  use: false
model:
  graph_pooling: mean
  loss_fun: l1
  type: GritTransformer
optim:
  base_lr: 0.0001
  clip_grad_norm: true
  max_epoch: 200
  num_warmup_epochs: 10
  optimizer: adamW
  scheduler: cosine_with_warmup
  weight_decay: 0.0
out_dir: results/LR_sweep
posenc_RRWP:
  add_identity: true
  add_inverse: false
  add_node_attr: false
  enable: false
  ksteps: 24
train:
  batch_size: 16
  ckpt_period: 100
  eval_period: 1
  mode: custom
wandb:
  entity: jiaqing
  group: LR-Sweep-Grit-All
  name: peptides-struct-noPE-LR0.0001
  project: PEGT
  use: true
