dataset:
  edge_encoder: true
  edge_encoder_bn: false
  edge_encoder_name: VOCEdge
  format: PyG-VOCSuperpixels
  name: edge_wt_region_boundary
  node_encoder: true
  node_encoder_bn: false
  node_encoder_name: VOCNode
  slic_compactness: 30
  task: graph
  task_type: classification
  transductive: false
gnn:
  act: gelu
  agg: mean
  batchnorm: true
  dim_inner: 64
  dropout: 0.1
  head: inductive_node
  layers_post_mp: 2
  layers_pre_mp: 0
  normalize_adj: false
gt:
  attn:
    O_e: true
    act: relu
    clamp: 5.0
    edge_enhance: true
    full_attn: false
    fwl: false
    norm_e: true
  attn_dropout: 0.2
  batch_norm: true
  dim_hidden: 64
  dropout: 0.0
  layer_norm: false
  layer_type: GritTransformer
  layers: 10
  n_heads: 8
  sparse: true
  update_e: true
metric_best: f1
mlflow:
  use: false
model:
  loss_fun: weighted_cross_entropy
  type: GritTransformer
optim:
  base_lr: 0.001
  clip_grad_norm: true
  max_epoch: 300
  num_warmup_epochs: 10
  optimizer: adamW
  scheduler: cosine_with_warmup
  weight_decay: 0.0
out_dir: results
posenc_EquivStableLapPE:
  dim_pe: 16
  eigen:
    eigvec_norm: L2
    laplacian_norm: none
    max_freqs: 10
  enable: false
  layers: 2
  model: DeepSet
  raw_norm_type: none
posenc_RRWP:
  enable: true
train:
  batch_size: 16
  ckpt_period: 100
  eval_period: 1
  mode: custom
wandb:
  entity: jiaqing
  name: VOC-GRIT-RRWP-Sparse
  project: PEGT
  use: true
