accelerator: cuda:0
dataset:
  edge_encoder: true
  edge_encoder_bn: false
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 4
  format: PyG-IMDB
  name: MULTI
  node_encoder: true
  node_encoder_bn: false
  node_encoder_name: LinearNode+LapPE
  node_encoder_num_types: 1
  task: node
  task_type: classification
  transductive: false
gnn:
  act: relu
  agg: mean
  batchnorm: true
  dim_inner: 64
  dropout: 0.0
  head: inductive_node
  layer_type: generalconv
  layers_post_mp: 3
  layers_pre_mp: 1
  normalize_adj: false
  stage_type: stack
graph_gym:
  max_epoch: 400
gt:
  attn:
    O_e: true
    act: relu
    clamp: 5.0
    edge_enhance: true
    full_attn: false
    fwl: false
    norm_e: true
  attn_dropout: 0.2
  batch_norm: true
  dim_hidden: 64
  dropout: 0.0
  layer_norm: false
  layer_type: GritTransformer
  layers: 3
  n_heads: 8
  sparse: true
  update_e: true
metric_agg: argmax
metric_best: f1
mlflow:
  use: false
model:
  edge_decoding: dot
  graph_pooling: none
  loss_fun: cross_entropy
  type: GritTransformer
num_workers: 4
out_dir: results
posenc_LapPE:
  dim_pe: 16
  eigen:
    eigvec_norm: L2
    laplacian_norm: none
    max_freqs: 10
  enable: true
  layers: 2
  model: DeepSet
  raw_norm_type: none
train:
  batch_size: 32
  ckpt_period: 100
  eval_period: 1
  mode: custom
wandb:
  entity: sihang-personal
  group: GRIT-Sparse-Dense-Final
  name: IMDB-GRIT-LapPE-Sparse
  project: PEGT
  use: true
