out_dir: results
metric_best: f1
metric_agg: argmax
accelerator: "cuda:0"
num_workers: 4
wandb:
  use: True
  project: PEGT
  name: "IMDB-GRITSparse-noPE"
  entity: sihang-personal
dataset:
  format: PyG-IMDB
  name: MULTI
  task: node
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode+noPE
  node_encoder_num_types: 1
  node_encoder_bn: False
  edge_encoder: False
posenc_RWSE:
  enable: False
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: GritTransformer
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: none
gnn:
  head: inductive_node
  layers_pre_mp: 1
  layers_post_mp: 3
  dim_inner: 64
  layer_type: generalconv
  stage_type: stack
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
graph_gym:
  max_epoch: 400
