accelerator: cuda:0
dataset:
  edge_encoder: true
  edge_encoder_bn: false
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 4
  format: PyG-ZINC
  name: subset
  node_encoder: true
  node_encoder_bn: false
  node_encoder_name: TypeDictNode
  node_encoder_num_types: 28
  task: graph
  task_type: regression
  transductive: false
gnn:
  act: relu
  agg: mean
  batchnorm: true
  dim_inner: 64
  dropout: 0.0
  head: san_graph
  layers_post_mp: 3
  layers_pre_mp: 0
  normalize_adj: false
gt:
  attn:
    O_e: true
    act: relu
    clamp: 5.0
    edge_enhance: true
    full_attn: false
    fwl: false
    norm_e: true
  attn_dropout: 0.1
  batch_norm: true
  dim_hidden: 64
  dropout: 0.1
  layer_norm: false
  layer_type: GAT+None
  layers: 10
  n_heads: 4
  update_e: true
metric_agg: argmin
metric_best: mae
model:
  edge_decoding: dot
  graph_pooling: add
  loss_fun: l1
  type: GPSModel
num_workers: 4
optim:
  base_lr: 0.0001
  clip_grad_norm: true
  max_epoch: 750
  min_lr: 1e-6
  num_warmup_epochs: 50
  optimizer: adamW
  scheduler: cosine_with_warmup
  weight_decay: 1e-5
out_dir: results
tensorboard_each_run: true
train:
  batch_size: 128
  ckpt_best: true
  ckpt_clean: true
  enable_ckpt: true
  eval_period: 1
  mode: custom
wandb:
  entity: sihang-personal
  group: ZINC-LR-Sweep
  name: ZINC-LR-1e-4-noPE
  project: PEGT
  use: true
