accelerator: cuda:0
dataset:
  edge_encoder: true
  edge_encoder_bn: false
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 4
  format: PyG-ZINC
  name: subset
  node_encoder: true
  node_encoder_bn: false
  node_encoder_name: TypeDictNode+GPSE
  node_encoder_num_types: 21
  task: graph
  task_type: regression
  transductive: false
gnn:
  act: relu
  agg: mean
  batchnorm: true
  dim_inner: 64
  dropout: 0.0
  head: san_graph
  layers_post_mp: 3
  layers_pre_mp: 0
  normalize_adj: false
gt:
  attn:
    O_e: true
    act: relu
    clamp: 5.0
    edge_enhance: true
    full_attn: false
    fwl: false
    norm_e: true
  attn_dropout: 0.2
  batch_norm: true
  dim_hidden: 64
  dropout: 0.0
  layer_norm: false
  layer_type: GritTransformer
  layers: 10
  'n_heads:': 8
  sparse: true
  update_e: true
metric_agg: argmin
metric_best: mae
model:
  edge_decoding: dot
  graph_pooling: add
  loss_fun: l1
  type: GritTransformer
optim:
  base_lr: 0.005
  clip_grad_norm: true
  'max_epoch:': 700
  min_lr: 1.0e-06
  num_warmup_epochs: 50
  optimizer: adamW
  scheduler: cosine_with_warmup
  weight_decay: 1.0e-05
out_dir: results
posenc_GPSE:
  dim_pe: 32
  enable: true
  gnn_cfg:
    act: relu
    agg: mean
    batchnorm: true
    dim_inner: 512
    dropout: 0.2
    head: inductive_hybrid_multi
    layer_type: resgatedgcnconv
    layers_mp: 20
    layers_post_mp: 2
    layers_pre_mp: 1
    multi_head_dim_inner: 32
    normalize_adj: false
    stage_type: skipsum
  input_dropout_ae: 0.0
  input_dropout_be: 0.5
  layers: 2
  model: mlp
  model_dir: /root/GT_PE/Benchmarking-PEs/pretrained/gpse_model_molpcba_1.0.pt
  rand_type: NormalSE
  raw_norm_type: BatchNorm
  repr_type: no_post_mp
  use_repr: true
  virtual_node: true
train:
  batch_size: 128
  ckpt_best: true
  ckpt_clean: true
  'enable_ckpt:': true
  eval_period: 1
  mode: custom
wandb:
  entity: sihang-personal
  name: ZINC-GRIT-GPSE-LR-0.005-Sparse
  project: PEGT
  use: true
